---
title: "Homework 1: Getting to Know Each Other"
author: "FIRSTNAME LASTNAME"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

```{r setup, include=FALSE}
#This code chunk is for modifying the global options and for loading required R packages
knitr::opts_chunk$set(echo = TRUE)
library(rmarkdown)
library(tinytex)
library(knitr)
```

# Instructions:

The purpose of this homework assignment is to get to know a student in the class, communicate the information learned in writing, and check to see if R Markdown is properly knitting to PDF. Start by putting your full name in the space provided above in the RMarkdown file (Replace FIRSTNAME and LASTNAME).

In this first homework, you will interview another student in the class and record this information in the appropriate space below. Find 2 or 3 students in the classroom to interview. If you are in a group of 3, make sure you work in a circle where person 1 interviews person 2, person 2 interviews person 3, and person 3 interviews person 1. *If you are uncomfortable talking with others or you join the class late, you can complete the homework assignment with your own answers.*

Don't just get the answers required, but actually get to know them. On the last question, I want you to replace what I wrote with a high quality question of your choice based off what you learned from listening to the person you interviewed.

After you are done, knit the RMarkdown file to PDF and submit the PDF to Gradescope under HW1.

# Interview:

- Name of Student:

- Origin:

- Year in School:

- Major or Minor:

- Involvement on Campus:

- Plans After Graduation:

- Biggest Influence in Your Life:

- Favorite Thing to Do in Your Free Time:

- REPLACE_WITH_CUSTOM_QUESTION_YOU_CREATED:



