---
title: "Supplement for Lecture 22: One-Way ANOVA"
output:
  pdf_document: default
---

```{r setup, include=FALSE}
#This code chunk is for modifying the global options and for loading required R packages
knitr::opts_chunk$set(echo = TRUE)
options(scipen=999) #Prevents the use of scientific notation

library(Stat2Data)
library(mosaic)

```

# Load Data 

```{r, message=FALSE}
Exams = read.csv("Exams4.csv")
Exams
```

# Examine Average Grades of Different Exams

```{r,eval=F}
# Overall Statistics of Grade
COMPLETE

# Group Statistics of Grade
COMPLETE

# Create Table
rbind(cbind(length,average,st.dev),overall)

# Create Visual
boxplot(Grade~Exam,data=Exams)
points(average,col="red",pch=16,cex=2)
```

# ANOVA For Testing Differences in Mean Grades for the Different Exams

```{r,eval=F}
# Visual
plot(Grade ~ Exam, data = Exams)
points(average, col="red", pch=16,cex=1.5)

# SST vs SSE vs SSGroups
COMPLETE

#ANOVA F-test
amodG = COMPLETE
summary(amodG)
```

# Checking Assumptions

```{r,eval=F}
plot(amodG) #Check Plots of Residuals

tapply(Exams$Grade, Exams$Exam, sd) #Is Largest More than Double Smallest
COMPLETE
```

